/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliotekabd;
import java.awt.Color;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
/**
 *
 * @author bvc
 */
public class Worker extends javax.swing.JFrame {

    /**
     * Creates new form Worker
     */
    
    public Connection workerconn;
    
     public static String[] zaprosi ={
        "select id, book_id,client_id, date_beg, date_end, date_ret from journal",
        "select * from clients",
        "select * from books",
        "select * from book_types",
        
        "select MAX(round(cast(DATE_RET as date)-cast(DATE_END as date))*book_types.FINE) as maxFine from (Journal join Books on Journal.BOOK_ID=Books.ID)join book_types on Books.TYPE_ID = book_types.ID where DATE_RET>DATE_END",
        "select book_id from (select book_id from JOURNAL group by book_id order by count(book_id) DESC,book_id ASC) where rownum<4"
        
    };
    
    
    public Worker() {
        initComponents();
    }

    void getconn(Connection conn){
        workerconn= conn;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_main = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        combo_sql = new javax.swing.JComboBox<>();
        button_journal = new javax.swing.JButton();
        textfield_book_in = new javax.swing.JTextField();
        button_book_in = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_journal = new javax.swing.JTable();
        button_sql = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_clients = new javax.swing.JTable();
        button_clients = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_books = new javax.swing.JTable();
        button_books = new javax.swing.JButton();
        textfield_client_id = new javax.swing.JTextField();
        button_client_books = new javax.swing.JButton();
        button_client_fine = new javax.swing.JButton();
        label_client_books = new javax.swing.JLabel();
        label_client_fine = new javax.swing.JLabel();
        textfield_client_id2 = new javax.swing.JTextField();
        button_client_delete = new javax.swing.JButton();
        textfield_book_id = new javax.swing.JTextField();
        button_book_delete = new javax.swing.JButton();
        button_client_change = new javax.swing.JButton();
        button_book_change = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_main.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(table_main);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Библиотекарь");

        combo_sql.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Вывести все записи журнала", "Вывести всех читателей", "Вывести все книги", "Вывести все типы книг", "Размер самого большого штрафа", "Вывести три самые популярные книги" }));

        button_journal.setText("Выдать книгу");
        button_journal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_journalActionPerformed(evt);
            }
        });

        button_book_in.setText("Принять книгу");
        button_book_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_book_inActionPerformed(evt);
            }
        });

        table_journal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "BOOK_ID", "CLIENT_ID"
            }
        ));
        jScrollPane2.setViewportView(table_journal);

        button_sql.setText("Вывести");
        button_sql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_sqlActionPerformed(evt);
            }
        });

        table_clients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
            },
            new String [] {
                "FIRST_NAME", "LAST_NAME", "FATHER_NAME", "PASSPORT_SERIA","PASSPORT_NUM"
            }
        ));
        jScrollPane3.setViewportView(table_clients);

        button_clients.setText("Добавить читателя");
        button_clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clientsActionPerformed(evt);
            }
        });

        table_books.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "NAME", "CNT", "TYPE_ID"
            }
        ));
        jScrollPane4.setViewportView(table_books);

        button_books.setText("Добавить книгу");
        button_books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_booksActionPerformed(evt);
            }
        });

        button_client_books.setText("Число книг на руках");
        button_client_books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_client_booksActionPerformed(evt);
            }
        });

        button_client_fine.setText("Размер штрафа");
        button_client_fine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_client_fineActionPerformed(evt);
            }
        });

        textfield_client_id2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_client_id2ActionPerformed(evt);
            }
        });

        button_client_delete.setText("Удалить читателя");
        button_client_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_client_deleteActionPerformed(evt);
            }
        });

        button_book_delete.setText("Удалить книгу");
        button_book_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_book_deleteActionPerformed(evt);
            }
        });

        button_client_change.setText("Изменить данные");
        button_client_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_client_changeActionPerformed(evt);
            }
        });

        button_book_change.setText("Изменить книгу");
        button_book_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_book_changeActionPerformed(evt);
            }
        });

        jLabel2.setText("Введите id читателя:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(378, 378, 378))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                                    .addComponent(combo_sql, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button_sql, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button_journal)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(button_clients, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(textfield_book_in, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(37, 37, 37)
                                                .addComponent(button_book_in))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textfield_client_id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(button_client_fine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(button_client_books, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(label_client_fine, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                                    .addComponent(label_client_books, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addComponent(button_books, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane3))
                                        .addGap(52, 52, 52)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button_client_change, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button_book_change, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button_client_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textfield_client_id2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button_book_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textfield_book_id, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_sql, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_sql, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_journal, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_book_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_book_in))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_client_delete)
                            .addComponent(textfield_client_id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(button_client_change)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_clients)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_book_delete)
                            .addComponent(textfield_book_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_book_change)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button_client_fine)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_books)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_client_books, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(button_client_books)
                                .addComponent(textfield_client_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_client_fine, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_booksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_booksActionPerformed
        // TODO add your handling code here:
        try{
        String name = (String)table_books.getValueAt(0,0); 
        int cnt = Integer.parseInt((String)table_books.getValueAt(0,1));
        int type_id = Integer.parseInt((String)table_books.getValueAt(0,2));
        
        Statement st = workerconn.createStatement();
       
        st.executeUpdate("INSERT INTO books (ID,NAME,CNT,TYPE_ID) "
                + "values(books_SEQ.NEXTVAL,'"+name+"','"+cnt+"','"+type_id+"')");
       
        button_books.setBackground(Color.green);
        
        }catch( Exception e )
        {
            System.out.print(e.getMessage());
             button_books.setBackground(Color.red); 
        }
        
    }//GEN-LAST:event_button_booksActionPerformed

    private void button_sqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_sqlActionPerformed
        // TODO add your handling code here:
        try{
         Statement st = workerconn.createStatement();
      
         int currentsql=0;
         
         if( combo_sql.getSelectedIndex()==0)
         {
          currentsql =0 ;
         }
         else if(combo_sql.getSelectedIndex()==1)
         {
         currentsql =1 ;
         }
         else if(combo_sql.getSelectedIndex()==2)
         {
         currentsql =2 ;
         }
         else if(combo_sql.getSelectedIndex()==3)
         {
            currentsql =3 ; 
         }
         else if(combo_sql.getSelectedIndex()==4)
         {
             currentsql =4 ;
         }
         else if( combo_sql.getSelectedIndex()==5)
         {
             currentsql =5 ;
         }
        
         ResultSet rs = st.executeQuery(zaprosi[currentsql]);
        
         ArrayList<ArrayList<String>> array = new ArrayList<ArrayList<String>>(); 
        
        int i=0;
        int c = rs.getMetaData().getColumnCount();
        String[] headers = new String[c];
        for( int m =0;m<c;m++){
        headers[m]=rs.getMetaData().getColumnName(m+1);
        }
        
         while (rs.next()) {
             array.add(new ArrayList<String>());
             for(int j =0 ; j< c; j++ )
             {
             array.get(i).add(rs.getString(j+1));
             }
             i++;
         }
         Object[][] data = new String[i][c];
         for( int m =0; m<i;m++)
         {
         for(int n=0; n<c;n++)
         {
             data[m][n]=array.get(m).get(n);
             //System.out.println(array.get(m).get(n));
         }
         }
        //guesttable = new javax.swing.JTable(data, headers);
        table_main.setModel(new javax.swing.table.DefaultTableModel( data, headers ));
        }
        catch( Exception e){
                
                }
    }//GEN-LAST:event_button_sqlActionPerformed

    private void button_journalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_journalActionPerformed
        // TODO add your handling code here:
        try{
        int book_id = Integer.parseInt((String)table_journal.getValueAt(0,0));
        int client_id = Integer.parseInt((String)table_journal.getValueAt(0,1));
       /* String date_beg = (String)table_journal.getValueAt(0,2);
        String date_end = (String)table_journal.getValueAt(0,3); */  
        
        
        Statement st = workerconn.createStatement();
       //чтоб вывести дату: to_date('11.05.2015','dd.MM.YY'); примерно как- то так
       st.executeUpdate("INSERT INTO journal ( id, book_id, client_id, date_beg, date_end) "
                + "values(JOURNAL_SEQ.NEXTVAL,'"+book_id+"','"+client_id+"',CURRENT_TIMESTAMP,(select (CURRENT_TIMESTAMP + BOOK_TYPES.DAY_COUNT) from BOOKS join BOOK_TYPES on BOOKS.TYPE_ID=Book_types.id where books.ID= '"+book_id+"'))");
       
        button_journal.setBackground(Color.green);
        }catch( Exception e )
        {
            System.out.print(e.getMessage());
            button_journal.setBackground(Color.red);
        }
    }//GEN-LAST:event_button_journalActionPerformed

    private void button_book_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_book_inActionPerformed
        // TODO add your handling code here:
        try{
        int journal_id = Integer.parseInt(textfield_book_in.getText()); 
        
         Statement statement = workerconn.createStatement();
        statement.executeUpdate("update journal  set date_ret = CURRENT_TIMESTAMP where id = '"+journal_id+"' and date_ret is null");
        
        button_book_in.setBackground(Color.green);
        }
        catch( Exception e )
        {
             System.out.print(e.getMessage());
             button_book_in.setBackground(Color.red); 
        }
        
    }//GEN-LAST:event_button_book_inActionPerformed

    private void button_clientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clientsActionPerformed
        // TODO add your handling code here:
        try{
        String first_name = (String)table_clients.getValueAt(0,0);
        String last_name = (String)table_clients.getValueAt(0,1);
        String father_name = (String)table_clients.getValueAt(0,2); 
        int passport_seria = Integer.parseInt((String)table_clients.getValueAt(0,3));
        int passport_num = Integer.parseInt((String)table_clients.getValueAt(0,4));
        
        Statement st = workerconn.createStatement();
       
        st.executeUpdate("INSERT INTO clients (ID,FIRST_NAME,LAST_NAME,FATHER_NAME,PASSPORT_SERIA,PASSPORT_NUM) "
                + "values(clients_SEQ.NEXTVAL,'"+first_name+"','"+last_name+"','"+father_name+"','"+passport_seria+"','"+passport_num+"')");
       
        button_clients.setBackground(Color.green);
        
        }catch( Exception e )
        {
            System.out.print(e.getMessage());
             button_clients.setBackground(Color.red); 
        }
        
    }//GEN-LAST:event_button_clientsActionPerformed

    private void button_client_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_client_deleteActionPerformed
        // TODO add your handling code here:
         try{
        int client_id = Integer.parseInt(textfield_client_id2.getText()); 
        
         Statement st = workerconn.createStatement();
        st.executeUpdate("delete from journal where CLIENT_ID= '"+client_id+"'");
        st.executeUpdate("delete from CLIENTS where ID='"+client_id+"'");
                
        button_client_delete.setBackground(Color.green);
        }
        catch( Exception e )
        {
             System.out.print(e.getMessage());
             button_client_delete.setBackground(Color.red); 
        }
    }//GEN-LAST:event_button_client_deleteActionPerformed

    private void textfield_client_id2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_client_id2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_client_id2ActionPerformed

    private void button_client_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_client_changeActionPerformed
        // TODO add your handling code here:
        try{
        int client_id = Integer.parseInt(textfield_client_id2.getText());
        
        String first_name = (String)table_clients.getValueAt(0,0);
        String last_name = (String)table_clients.getValueAt(0,1);
        String father_name = (String)table_clients.getValueAt(0,2); 
        int passport_seria = Integer.parseInt((String)table_clients.getValueAt(0,3));
        
        Statement st = workerconn.createStatement();
        st.executeUpdate("update clients  set FIRST_NAME ='"+first_name+"' ,LAST_NAME='"+last_name+"',FATHER_NAME='"+father_name+"',PASSPORT_SERIA='"+passport_seria+"' where id = '"+client_id+"'");
    
        button_client_change.setBackground(Color.green);
        }
        catch( Exception e )
        {
             System.out.print(e.getMessage());
             button_client_change.setBackground(Color.red); 
        }
    }//GEN-LAST:event_button_client_changeActionPerformed

    private void button_book_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_book_deleteActionPerformed
        // TODO add your handling code here:
        
           try{
        int book_id = Integer.parseInt(textfield_book_id.getText()); 
        
         Statement st = workerconn.createStatement();
        st.executeUpdate("delete from journal where BOOK_ID= '"+book_id+"'");
        st.executeUpdate("delete from books where ID='"+book_id+"'");
                
        button_book_delete.setBackground(Color.green);
        }
        catch( Exception e )
        {
             System.out.print(e.getMessage());
             button_book_delete.setBackground(Color.red); 
        }
        
    }//GEN-LAST:event_button_book_deleteActionPerformed

    private void button_book_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_book_changeActionPerformed
        // TODO add your handling code here:
        
         try{
        int book_id = Integer.parseInt(textfield_book_id.getText());
        
        String name = (String)table_books.getValueAt(0,0); 
        int cnt = Integer.parseInt((String)table_books.getValueAt(0,1));
        int type_id = Integer.parseInt((String)table_books.getValueAt(0,2));
        
        Statement st = workerconn.createStatement();
        st.executeUpdate("update books  set NAME ='"+name+"' ,cnt='"+cnt+"',type_id='"+type_id+"' where id = '"+book_id+"'");
    
        button_book_change.setBackground(Color.green);
        }
        catch( Exception e )
        {
             System.out.print(e.getMessage());
             button_book_change.setBackground(Color.red); 
        }
        
    }//GEN-LAST:event_button_book_changeActionPerformed

    private void button_client_booksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_client_booksActionPerformed
        // TODO add your handling code here:
        try{
        int client_id = Integer.parseInt(textfield_client_id.getText());
        String books_count = "";
        
        Statement st = workerconn.createStatement();
       
         ResultSet rs = st.executeQuery("select count(client_id)from Journal where DATE_RET is NULL and CLIENT_ID = '"+client_id+"'");
              
         while (rs.next()) {
            books_count= rs.getString(1);
         }
         
         label_client_books.setText(books_count);
         button_client_books.setBackground(Color.green);
         
        }catch( Exception e ){
            System.out.print(e.getMessage());
             button_client_books.setBackground(Color.red); 
        }
        
    }//GEN-LAST:event_button_client_booksActionPerformed

    private void button_client_fineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_client_fineActionPerformed
        // TODO add your handling code here:
         try{
        int client_id = Integer.parseInt(textfield_client_id.getText());
        String fine_count = "";
        
        Statement st = workerconn.createStatement();
       
         ResultSet rs = st.executeQuery("select SUM(round(cast(DATE_RET as date)-cast(DATE_END as date))*book_types.FINE) from (Journal join Books on Journal.BOOK_ID=Books.ID)join book_types on Books.TYPE_ID = book_types.ID where DATE_RET>DATE_END and CLIENT_ID = '"+client_id+"'");
              
         while (rs.next()) {
            fine_count= rs.getString(1);
         }
         
         label_client_fine.setText(fine_count);
         button_client_fine.setBackground(Color.green);
         
        }catch( Exception e ){
            System.out.print(e.getMessage());
             button_client_fine.setBackground(Color.red); 
        }
        
    }//GEN-LAST:event_button_client_fineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Worker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_book_change;
    private javax.swing.JButton button_book_delete;
    private javax.swing.JButton button_book_in;
    private javax.swing.JButton button_books;
    private javax.swing.JButton button_client_books;
    private javax.swing.JButton button_client_change;
    private javax.swing.JButton button_client_delete;
    private javax.swing.JButton button_client_fine;
    private javax.swing.JButton button_clients;
    private javax.swing.JButton button_journal;
    private javax.swing.JButton button_sql;
    private javax.swing.JComboBox<String> combo_sql;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label_client_books;
    private javax.swing.JLabel label_client_fine;
    private javax.swing.JTable table_books;
    private javax.swing.JTable table_clients;
    private javax.swing.JTable table_journal;
    private javax.swing.JTable table_main;
    private javax.swing.JTextField textfield_book_id;
    private javax.swing.JTextField textfield_book_in;
    private javax.swing.JTextField textfield_client_id;
    private javax.swing.JTextField textfield_client_id2;
    // End of variables declaration//GEN-END:variables
}
